export const SET_CATEGORIES_LIST = 'SET_CATEGORIES_LIST';
export const SET_NEWS_LIST = 'SET_NEWS_LIST';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const SET_DETAILED_NEWS_ITEM = 'SET_DETAILED_NEWS_ITEM';
export const START_CATEGORIES_REQUEST = 'START_CATEGORIES_REQUEST';
export const STOP_CATEGORIES_REQUEST = 'STOP_CATEGORIES_REQUEST';
